# Generated by Django 4.1.7 on 2023-03-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('password_id', models.CharField(max_length=16)),
                ('social_login', models.CharField(max_length=2083)),
                ('contact_number', models.CharField(max_length=11)),
                ('house_number', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('pin_location', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='OrderContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_timestamp', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_name', models.CharField(max_length=255)),
                ('order_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.CharField(max_length=100)),
                ('discount_type', models.CharField(max_length=50)),
                ('discount_details', models.CharField(max_length=100)),
                ('tax', models.IntegerField()),
                ('order_total', models.FloatField()),
                ('contact_number', models.CharField(max_length=11)),
                ('house_number', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('pin_location', models.CharField(max_length=2083)),
                ('shipping_time', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ordercontents')),
            ],
        ),
        migrations.AddField(
            model_name='ordercontents',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
